zip: fix

diff --git a/zip/META-INF/com/google/android/update-binary b/zip/META-INF/com/google/android/update-binary
--- a/zip/META-INF/com/google/android/update-binary
+++ b/zip/META-INF/com/google/android/update-binary
@@ -148,6 +148,10 @@ done;
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
   abort "Recovery busybox setup failed. Aborting...";
 fi;
+cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
+if [ $? != "0" ]; then
+  abort "DTB append failed. Aborting...";
+fi;
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
   abort;
